##
##	A clone of a famous game.
##
##	Makefile	-	The make file (3 level).
##
##	(c) Copyright 1998,1999 by Lutz Sammer
##
##	$Id$
##

TOPDIR	= ../..

include $(TOPDIR)/Rules.make

MODULE	= sound
OBJS	= sound.$(OE) sound_server.$(OE) ccl_sound.$(OE) sound_id.$(OE) \
	  unitsound.$(OE)

include $(TOPDIR)/Common.mk
