##   ___________		     _________		      _____  __
##   \_	  _____/______   ____   ____ \_   ___ \____________ _/ ____\/  |_
##    |    __) \_  __ \_/ __ \_/ __ \/    \  \/\_  __ \__  \\   __\\   __\
##    |     \   |  | \/\  ___/\  ___/\     \____|  | \// __ \|  |   |  |
##    \___  /   |__|    \___  >\___  >\______  /|__|  (____  /__|   |__|
##	  \/		    \/	   \/	     \/		   \/
##  ______________________                           ______________________
##			  T H E   W A R   B E G I N S
##	   FreeCraft - A free fantasy real time strategy game engine
##
##	Makefile	-	The make file (3 level).
##
##	(c) Copyright 1998,2000,2001 by Lutz Sammer
##
##	FreeCraft is free software; you can redistribute it and/or modify
##	it under the terms of the GNU General Public License as published
##	by the Free Software Foundation; either version 2 of the License,
##	or (at your option) any later version.
##
##	FreeCraft is distributed in the hope that it will be useful,
##	but WITHOUT ANY WARRANTY; without even the implied warranty of
##	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##	GNU General Public License for more details.
##
##	$Id$
##

TOPDIR	= ../..

include $(TOPDIR)/Rules.make

MODULE  = action

OBJS	= command.$(OE) actions.$(OE) action_die.$(OE) action_patrol.$(OE) \
	action_still.$(OE) action_stand.$(OE) action_move.$(OE) \
	action_follow.$(OE) action_attack.$(OE) action_resource.$(OE) \
	action_board.$(OE) action_unload.$(OE) action_repair.$(OE) \
	action_harvest.$(OE) action_minegold.$(OE) \
	action_returngoods.$(OE) action_research.$(OE) action_demolish.$(OE) \
	action_build.$(OE) action_train.$(OE) action_upgradeto.$(OE) \
	action_spellcast.$(OE)

include $(TOPDIR)/Common.mk
