##
##	A clone of a famous game.
##
##	Makefile	-	The make file (3 level).
##
##	(c) Copyright 1998 by Lutz Sammer
##
##	$Id$
##

TOPDIR	= ../..

include $(TOPDIR)/Rules.make

MODULE	= network
OBJS	= network.$(OE)

include $(TOPDIR)/Common.mk
