.TH STRATAGUS 6 "Oct 2011" "Stratagus v2.2.7"
.SH NAME
stratagus \- Strategy Gaming Engine
.SH SYNOPSIS
.B stratagus
.I [-c file.lua] [-d datapath] [-D depth] [-e] [-E file.lua] [-F|-W] [-h] [-I addr] [-l] [-L lag] [-n server]
.I [-N name] [-o|-O] [-P port] [-s sleep] [-S speed] [-U update] [-v mode] [map.smp|map.smp.gz]
.SH "DESCRIPTION"
This manual page documents briefly the flags that you can give to
.BR stratagus
, formerly known as FreeCraft, formerly known as ALE Clone.
.PP
.B stratagus
is a powerful game engine for building realtime strategy games, a la AoE or Warcraft.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-c file.lua
Choose a different stratagus start config file.
.TP
.B \-d datapath
Choose a different directory to use for game data files.
.TP
.B \-D depth
Set the video mode depth, often called 'bpp' or 'bits per pixel'. This
option is only valid for Win32/NT.
.TP
.B \-e
Start the editor included in Stratagus.
.TP
.B \-E
Choose a different editor config file.
.TP
.B \-F
With this option you can start Stratagus in full screen video mode.
.TP
.B \-h
Show summary of all options.
.TP
.B \-I addr
With this option you can specify the network address for network play.
.TP
.B \-l
Disable command log messages.
.TP
.B \-L lag
This sets the network lag in number of frames (default 10 = 333 ms).
.TP
.B \-n server
With this option you can specify the network server host for network play.
.TP
.B \-N name
The name of the player (will appear in network games).
.TP
.B \-O
Use OpenGL or OpenGL ES 1.1.
.TP
.B \-o
Do not use OpenGL or OpenGL ES 1.1.
.TP
.B \-P port
With this option you can set the network port to use in network games.
The default value is port udp/6660.
.TP
.B \-s number
Number of frames before AI awakes. This is useful if the AI is beating
you hard, and you want to make it sweet like a cat. The higher, the easier
will be the game against the AI. Default is to sleep 0 time frames.
.TP
.B \-S number
Sync speed (100 = 30 frames/s).
.TP
.B \-U update
With this option you can specify the network update rate in # frames (default 5=6x per s).
.TP
.B \-v mode
With this option you can specify video mode resolution in format \fB<xres>\fRx\fB<yres>\fR
.TP
.B \-W
With this option you can start Stratagus in windowed video mode.
.SH "FILES"
.TP
.B ./
Default directory for Stratagus data files
.TP
.B ./scripts/stratagus.lua
Default start config file.
.TP
.B ./scripts/editor.lua
Default editor file.
.TP
.B ./scripts/guichan.lua
Default menu file.
.TP
.B ~/.stratagus/<data>/preferences.lua
User preferences configuration file for <data>
.TP
.B ~/.stratagus/<data>/logs/
User directory with replays/logs for <data>
.TP
.B ~/.stratagus/<data>/save/
User directory with saved games for <data>
.SH "SEE ALSO"
More complete documentation is available in /usr/share/doc/stratagus.
.SH NOTES
Stratagus needs a lot of data (maps and artwork), that can come from
external datasets, like Battle of Survival (BoS), or even from the media
in the Warcraft II CD, thanks to the Wargus dataset.
.PP
Warcraft II is a registered trademark of Blizzard Entertainment.
.SH AUTHOR
Stratagus is written by Nehal Mistry, Russell Smith, Pali Rohár and others.
.PP
This manual page was written by Anthony Towns <ajt@debian.org>,
David Martínez Moreno <ender@debian.org> and
Pali Rohár <pali.rohar@gmail.com> for the Debian GNU/Linux
system (but may be used by others).
