##   ___________		     _________		      _____  __
##   \_	  _____/______   ____   ____ \_   ___ \____________ _/ ____\/  |_
##    |    __) \_  __ \_/ __ \_/ __ \/    \  \/\_  __ \__  \\   __\\   __\ 
##    |     \   |  | \/\  ___/\  ___/\     \____|  | \// __ \|  |   |  |
##    \___  /   |__|    \___  >\___  >\______  /|__|  (____  /__|   |__|
##	  \/		    \/	   \/	     \/		   \/
##  ______________________                           ______________________
##			  T H E   W A R   B E G I N S
##	   FreeCraft - A free fantasy real time strategy game engine
##
##	Makefile	-	The make file (3 level).
##
##	(c) Copyright 1998-2001 by Lutz Sammer
##
##	siod.h siodp.h from SIOD - Scheme In One Day interpreter.
##		Copyright and Author: George J. Carrette, gjc@delphi.com
##
##	FreeCraft is free software; you can redistribute it and/or modify
##	it under the terms of the GNU General Public License as published
##	by the Free Software Foundation; either version 2 of the License,
##	or (at your option) any later version.
##
##	FreeCraft is distributed in the hope that it will be useful,
##	but WITHOUT ANY WARRANTY; without even the implied warranty of
##	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##	GNU General Public License for more details.
##
##	$Id$
##

TOPDIR= ../..
include $(TOPDIR)/Rules.make

MODULE	= include

OBJS	=

HDRS	= actions.h ai.h ccl.h freecraft.h construct.h cursor.h font.h icons.h \
	  image.h interface.h map.h minimap.h missile.h pathfinder.h player.h \
	  pud.h tileset.h unit.h unittype.h upgrade.h upgrade_structs.h \
	  ccl_sound.h sound.h sound_id.h unitsound.h wav.h sound_server.h \
	  video.h network.h commands.h goal.h ui.h menus.h spells.h \
	  siod.h siodp.h iolib.h depend.h settings.h myendian.h net_lowlevel.h \
	  netconnect.h rdtsc.h \
	  etlib/generic.h etlib/xmalloc.h etlib/hash.h etlib/dllist.h \

all:
	echo done.

include $(TOPDIR)/Common.mk
