##
##	A clone of a famous game.
##
##	Makefile	-	The make file (3 level).
##
##	(c) Copyright 1999 by Lutz Sammer
##
##	$Id$
##

TOPDIR	= ../..

include $(TOPDIR)/Rules.make

MODULE  = pathfinder

OBJS	= pathfinder.$(OE) astar.$(OE) ccl_pathfinder.$(OE)

include $(TOPDIR)/Common.mk
