##   ___________		     _________		      _____  __
##   \_	  _____/______   ____   ____ \_   ___ \____________ _/ ____\/  |_
##    |    __) \_  __ \_/ __ \_/ __ \/    \  \/\_  __ \__  \\   __\\   __\ 
##    |     \   |  | \/\  ___/\  ___/\     \____|  | \// __ \|  |   |  |
##    \___  /   |__|    \___  >\___  >\______  /|__|  (____  /__|   |__|
##	  \/		    \/	   \/	     \/		   \/
##  ______________________                           ______________________
##			  T H E   W A R   B E G I N S
##	   FreeCraft - A free fantasy real time strategy game engine
##
##	Makefile	-	The make file (3 level).
##
##	(c) Copyright 1998,2000 by Lutz Sammer
##
##	$Id$
##

TOPDIR	= ../..

include $(TOPDIR)/Rules.make

##
## USER INTERFACE
##
## TODO: move here all user-interface-related files
##

MODULE	= ui
OBJS	= mouse.$(OE) button_table.$(OE) botpanel.$(OE) mainscr.$(OE) \
	  icons.$(OE) ui.$(OE) ccl_ui.$(OE) image.$(OE) menus.$(OE) \
	  console.$(OE)

include $(TOPDIR)/Common.mk
